version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gpt-app:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
