version: '3'
services:
  mongo:
    container_name: mongo-gptapp
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  gpt-app:
    container_name: node-gptapp
    build: .
    ports:
      - "${SERVER_PORT}:8000"
      - "${CLIENT_PORT}:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
